/* TABLE ABONNEMENT */

-- création de la table
CREATE TABLE ABONNEMENT (
    TYPEABONNEMENT VARCHAR(9) PRIMARY KEY,
    TARIF NUMBER(4, 2) NOT NULL
);

/

------------------------------------------------------------------

/* TABLE CLIENT */

-- création de la table
CREATE TABLE CLIENT (
    IDCLIENT NUMBER PRIMARY KEY,
    NOMCLIENT VARCHAR(60) NOT NULL,
    MOTDEPASSECLIENT VARCHAR(30) NOT NULL,
    AGECLIENT DATE NOT NULL,
    ADRESSEMAIL VARCHAR(320) NOT NULL,
    DATEINSCRIPTION DATE NOT NULL,
    IBAN CHAR(33),
    DATEPRELEVEMENT DATE CHECK (TO_NUMBER(TO_CHAR(DATEPRELEVEMENT, 'DD')) <= 28),
    TYPEABONNEMENT VARCHAR(9) NOT NULL REFERENCES ABONNEMENT(TYPEABONNEMENT)
);

/

------------------------------------------------------------------

/* TABLE PROFIL */

-- création de la table
CREATE TABLE PROFIL (
    IDCLIENT NUMBER REFERENCES CLIENT(IDCLIENT) ON DELETE CASCADE,
    IDPROFIL NUMBER(2),
    PSEUDO VARCHAR(20) NOT NULL,
    PHOTO BLOB,
    MOTDEPASSEPROFIL CHAR(4) CHECK (REGEXP_LIKE(MOTDEPASSEPROFIL, '^[0-9]{4}$')),
    AGEPROFIL DATE NOT NULL,
    TYPEPROFIL VARCHAR(6) NOT NULL CHECK(TYPEPROFIL IN ('Enfant', 'Adulte')),
    LANGUE VARCHAR(25) NOT NULL,
    SOUSTITRES NUMBER(1) DEFAULT 0 NOT NULL CHECK(SOUSTITRES BETWEEN 0 AND 1),
    PRIMARY KEY (IDCLIENT, IDPROFIL)
);

/

------------------------------------------------------------------

/* TABLE CONTENU */

-- création de la table
CREATE TABLE CONTENU (
    IDCONTENU NUMBER PRIMARY KEY,
    TITRECONTENU VARCHAR(60) NOT NULL,
    CLASSIFICATION VARCHAR(12) NOT NULL CHECK (CLASSIFICATION IN ('Tous publics', '-10 ans', '-12 ans', '-16 ans', '-18 ans')),
    DESCRIPTION VARCHAR(200),
    DISPONIBILITE VARCHAR(7) NOT NULL CHECK (DISPONIBILITE IN ('Gratuit', 'Payant')),
    LANGUEORIGINE VARCHAR(25) NOT NULL,
    TYPECONTENU VARCHAR(5) NOT NULL CHECK (TYPECONTENU IN ('Film', 'Série')),
    DATESORTIEFILM DATE,
    DUREEFILM NUMBER(3),
    ANNEESERIE NUMBER(4)
);

/

------------------------------------------------------------------

/* TABLE EPISODE */

-- création de la table
CREATE TABLE EPISODE (
    IDCONTENU NUMBER REFERENCES CONTENU(IDCONTENU),
    NUMSAISON NUMBER(2),
    NUMEPISODE NUMBER(3),
    TITREEPISODE VARCHAR(60) NOT NULL,
    DUREEEPISODE NUMBER(3) NOT NULL,
    DATESORTIEEPISODE DATE NOT NULL,
    PRIMARY KEY (IDCONTENU, NUMSAISON, NUMEPISODE)
);

/

------------------------------------------------------------------

/* TABLE PROFESSIONNEL */

-- création de la table
CREATE TABLE PROFESSIONNEL (
    IDPRO NUMBER PRIMARY KEY,
    NOMPRO VARCHAR(30) NOT NULL,
    PRENOMPRO VARCHAR(30) NOT NULL,
    NATIONALITE VARCHAR(25),
    AGEPRO DATE
);

/

------------------------------------------------------------------

/* TABLE CATEGORIE */

-- création de la table
CREATE TABLE CATEGORIE (
    NOMCATEGORIE VARCHAR(30) PRIMARY KEY
);

/

------------------------------------------------------------------
------------------------------------------------------------------

/* TABLE LECTUREFILM */

-- création de la table
CREATE TABLE LECTUREFILM (
    IDCLIENT NUMBER,
    IDPROFIL NUMBER(2),
    IDCONTENU NUMBER REFERENCES CONTENU(IDCONTENU),
    DATELECTURE DATE,
    TEMPSDEBUT DATE NOT NULL,
    TEMPSFIN DATE NOT NULL,
    LANGUE VARCHAR(25) NOT NULL,
    SOUSTITRES NUMBER(1) NOT NULL CHECK (SOUSTITRES BETWEEN 0 AND 1),
    PRIMARY KEY (IDCLIENT, IDPROFIL, IDCONTENU, DATELECTURE),
    FOREIGN KEY (IDCLIENT, IDPROFIL) REFERENCES PROFIL(IDCLIENT, IDPROFIL) ON DELETE CASCADE
);

/

------------------------------------------------------------------

/* TABLE LECTUREEP */

-- création de la table
CREATE TABLE LECTUREEP (
    IDCLIENT NUMBER,
    IDPROFIL NUMBER(2),
    IDCONTENU NUMBER,
    NUMSAISON NUMBER(2),
    NUMEPISODE NUMBER(3),
    DATELECTURE DATE,
    TEMPSDEBUT DATE NOT NULL,
    TEMPSFIN DATE NOT NULL,
    LANGUE VARCHAR(25) NOT NULL,
    SOUSTITRES NUMBER(1) NOT NULL CHECK (SOUSTITRES BETWEEN 0 AND 1),
    PRIMARY KEY (IDCLIENT, IDPROFIL, IDCONTENU, NUMSAISON, NUMEPISODE, DATELECTURE),
    FOREIGN KEY (IDCLIENT, IDPROFIL) REFERENCES PROFIL(IDCLIENT, IDPROFIL) ON DELETE CASCADE,
    FOREIGN KEY (IDCONTENU, NUMSAISON, NUMEPISODE) REFERENCES EPISODE(IDCONTENU, NUMSAISON, NUMEPISODE)
);

/

------------------------------------------------------------------

/* TABLE AVIS */

-- création de la table
CREATE TABLE AVIS (
    IDCLIENT NUMBER,
    IDPROFIL NUMBER(2),
    IDCONTENU NUMBER REFERENCES CONTENU(IDCONTENU),
    NOTE NUMBER(2) CHECK (NOTE BETWEEN 1 AND 10),
    COMMENTAIRE VARCHAR(1000),
    PRIMARY KEY (IDCLIENT, IDPROFIL, IDCONTENU),
    FOREIGN KEY (IDCLIENT, IDPROFIL) REFERENCES PROFIL(IDCLIENT, IDPROFIL) ON DELETE CASCADE
);

/

------------------------------------------------------------------

/* TABLE PARTICIPE */

-- création de la table
CREATE TABLE PARTICIPE (
    IDCONTENU NUMBER REFERENCES CONTENU(IDCONTENU),
    IDPRO NUMBER REFERENCES PROFESSIONNEL(IDPRO),
    PROFESSION VARCHAR(11) NOT NULL CHECK (PROFESSION IN ('Réalisateur', 'Acteur')),
    ROLE VARCHAR(10) NOT NULL CHECK (ROLE IN ('Principal', 'Secondaire')),
    PRIMARY KEY (IDCONTENU, IDPRO, PROFESSION)
);

/

------------------------------------------------------------------

/* TABLE DEFINIT */

-- création de la table
CREATE TABLE DEFINIT (
    IDCONTENU NUMBER REFERENCES CONTENU(IDCONTENU),
    NOMCATEGORIE VARCHAR(30) REFERENCES CATEGORIE(NOMCATEGORIE),
    PRIMARY KEY (IDCONTENU, NOMCATEGORIE)
);

/

------------------------------------------------------------------
------------------------------------------------------------------

/* VUES */

-- vue des contenus de type Film
CREATE OR REPLACE VIEW FILMS AS
    SELECT
        *
    FROM
        CONTENU
    WHERE
        TYPECONTENU = 'Film';

/

-- vue des contenus de type Série
CREATE OR REPLACE VIEW SERIES AS
    SELECT
        *
    FROM
        CONTENU
    WHERE
        TYPECONTENU = 'Série';

/

-- vue des films et des épisodes
CREATE OR REPLACE VIEW VIDEOS (
    IDCONTENU,
    DATESORTIE,
    TITRE,
    NUMSAISON,
    NUMEPISODE,
    TITREEPISODE
) AS
    SELECT
        IDCONTENU,
        DATESORTIEFILM,
        TITRECONTENU,
        NULL,
        NULL,
        NULL
    FROM
        FILMS
    UNION
    SELECT
        E.IDCONTENU,
        E.DATESORTIEEPISODE,
        S.TITRECONTENU,
        E.NUMSAISON,
        E.NUMEPISODE,
        E.TITREEPISODE
    FROM
        EPISODE E,
        SERIES  S
    WHERE
        E.IDCONTENU = S.IDCONTENU;

/