-- CREATION DES DIFFERENTS ROLES
CREATE ROLE ADMIN_USER;

CREATE ROLE CLIENT_USER;

CREATE ROLE PROFIL_USER;

-- AFFECTATION DES DIFFERENTS DROITS A L'ADMIN
GRANT ALL PRIVILEGES ON ABONNEMENT TO ADMIN_USER;

GRANT ALL PRIVILEGES ON CLIENT TO ADMIN_USER;

GRANT ALL PRIVILEGES ON PROFIL TO ADMIN_USER;

GRANT ALL PRIVILEGES ON CONTENU TO ADMIN_USER;

GRANT ALL PRIVILEGES ON CATEGORIE TO ADMIN_USER;

GRANT ALL PRIVILEGES ON PROFESSIONNEL TO ADMIN_USER;

GRANT ALL PRIVILEGES ON PARTICIPE TO ADMIN_USER;

GRANT ALL PRIVILEGES ON EPISODE TO ADMIN_USER;

GRANT ALL PRIVILEGES ON VIDEOS TO ADMIN_USER;

GRANT ALL PRIVILEGES ON FILMS TO ADMIN_USER;

GRANT ALL PRIVILEGES ON LECTUREEP TO ADMIN_USER;

GRANT ALL PRIVILEGES ON LECTUREFILM TO ADMIN_USER;

GRANT ALL PRIVILEGES ON AVIS TO ADMIN_USER;

GRANT ALL PRIVILEGES ON DEFINIT TO ADMIN_USER;

GRANT ALL PRIVILEGES ON PROFIL_VIEW TO ADMIN_USER;

GRANT ALL PRIVILEGES ON CLIENT_VIEW TO ADMIN_USER;

-- AFFECTATION DES DIFFERENTS DROITS AUX CLIENTS
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENT TO CLIENT_USER;

GRANT SELECT ON ABONNEMENT TO CLIENT_USER;

-- AFFECTATION DES DIFFERENTS DROITS AUX PROFILS
GRANT SELECT, INSERT, UPDATE, DELETE ON PROFIL TO PROFIL_USER;

GRANT SELECT ON CONTENU TO PROFIL_USER;

GRANT SELECT ON EPISODE TO PROFIL_USER;

GRANT SELECT ON VIDEOS TO PROFIL_USER;

GRANT SELECT ON FILMS TO PROFIL_USER;

GRANT SELECT ON SERIES TO PROFIL_USER;

GRANT SELECT ON PARTICIPE TO PROFIL_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON LECTUREEP TO PROFIL_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON LECTUREFILM TO PROFIL_USER;

GRANT SELECT ON CATEGORIE TO PROFIL_USER;

GRANT SELECT ON PROFESSIONNEL TO PROFIL_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON AVIS TO PROFIL_USER;

-- CREATION DE L'ADMIN
CREATE USER ADMIN_ID IDENTIFIED BY admin_mdp;

GRANT ADMIN_USER TO ADMIN_ID;