------------------------------------------------------------------

/* DROP TABLE */

DROP TABLE DEFINIT;

DROP TABLE PARTICIPE;

DROP TABLE AVIS;

DROP TABLE LECTUREEP;

DROP TABLE LECTUREFILM;

DROP TABLE CATEGORIE;

DROP TABLE PROFESSIONNEL;

DROP TABLE EPISODE;

DROP TABLE CONTENU;

DROP TABLE PROFIL;

DROP TABLE CLIENT;

DROP TABLE ABONNEMENT;

------------------------------------------------------------------

/* DROP VIEW */

DROP VIEW VIDEOS;

DROP VIEW FILMS;

DROP VIEW SERIES;

------------------------------------------------------------------

/* DROP SEQUENCE */

DROP SEQUENCE ID_PROF;

DROP SEQUENCE ID_CLI;

------------------------------------------------------------------

/* DROP PROCEDURE */

DROP PROCEDURE DATE_PRELEV;